### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by iamthesenate1**
I have updated the screenshots to show version 0.17.0, but as light.png is no longer used I deleted it. If I'm wrong, tell me, and I'll update it too.

### CODE REVIEW

**Comment by iamthesenate1** [comment]
Related: #64

**Comment by stefonarch** [comment]
They look fine to me, thanks!

**Comment by iamthesenate1** [comment]
You're welcome. I am happy to help.

**Comment by iamthesenate1** [comment]
Hi! Sorry if I seem rude by asking, but why is this not merged?

**Comment by stefonarch** [comment]
> Hi! Sorry if I seem rude by asking, but why is this not merged?

Good question, because I forgot and nobody else looked at it probably. Thanks!

**Pull request merged**
