### PR TITLE
Changed Distros's logos to SVG format 

### LINKED ISSUE #68: Distros's logos as svgs
Is there a reason why distros's logos are not svg? 
If not, I'd like to make a PR to change them.

### PR DESCRIPTION
**Pull request by iamthesenate1**
Closes #68. Sorry for the delay but some of them were really hard to find (I had to manually trace ROSA Linux one, for example)

### CODE REVIEW

**Comment by iamthesenate1** [comment]
Changed the LXQt logo to svg format too.

**Comment by iamthesenate1** [comment]
Sorry if I seem impolite, but is there a reason that this is not merged?

If it is, I would like to know so that I can fix the issue(s).

**Comment by tsujan** [comment]
> Sorry if I seem impolite.

It's absolutely polite :)

It might take a while before an LXQt member finds the time to review a PR. I'm an LXQt member but have open PRs from a month ago that aren't reviewed yet.

**Comment by iamthesenate1** [comment]
I understand. Thanks for explaining.

**Comment by tsujan** [comment]
@stefonarch, could you review it? I don't know much about the site.

**Review by stefonarch — CHANGES_REQUESTED** [review]
Archlinux logo has wrong filename and therefor isn't displayed.
Should be `archlinux-logo-22.svg
`

**Comment by iamthesenate1** [comment]
> Archlinux logo has wrong filename and therefor isn't displayed.
> Should be `archlinux-logo-22.svg `

Done.

> Some of the SVG files need maybe a cleanup.

Any one in particular? I retraced the ROSA Linux one, but I can't seem to be able to optimise much of the others.

**Review by stefonarch — COMMENTED** [review]
Looks like an issue with the mageia-logo-22.svg now, I see no problem  in  html:
schermata-07-16-22-29

**Comment by iamthesenate1** [comment]
> Looks like an issue with the mageia-logo-22.svg now, I see no problem in html:
> schermata-07-16-22-29

This should be fixed now.

**Review by stefonarch — APPROVED** [review]
Looks fine now, thanks!

**Comment by stefonarch** [comment]
I didn't notice it in my test, but rosa icon had the same issue now, I reverted the commit...
schermata-07-20-14-09

**Comment by iamthesenate1** [comment]
For me it works fine:
screen06
Can you test again?

> But IMHO it isn't a big issue using *.png icons on the website, I'm not sure if it is really worth **all this work and testing**.

IMO this is the exact reason to continue. Why give up after all this work?

**Comment by tsujan** [comment]
> but rosa icon had the same issue now

Its sizes are in mm, which is wrong.

**Comment by tsujan** [comment]
@iamthesenate1 

You could make another PR with the correct SVG icons (check their sizes).

And please don't commit every change that you make to the source (e.g., deleting something, then adding something else, then deleting another thing,...); *commit the changes together* (deleting+adding+deleting+... *as a single commit*)!

**Comment by iamthesenate1** [comment]
@tsujan Thank you for finding out the problem. I have opened #72 with the fixes.

**Pull request merged**
