### PR TITLE
Make Distros that don't have an updated version of lxqt red

### PR DESCRIPTION
**Pull request by iamthesenate1**

### CODE REVIEW

**Comment by stefonarch** [comment]
Not sure if that is a good idea. It's not our business which distro ships which version and flagging them red looks like a warning. and version 0.16 isn't that bad :)

Maybe better show in some more decent matter which distro ship the latest version.

**Comment by tsujan** [comment]
I agree with @stefonarch.

Also, distro maintainers might change.

**Comment by iamthesenate1** [comment]
Ok. I see your point.

**Comment by iamthesenate1** [comment]
One half-related thing is that from what I could find ROSA Linux still has version 0.11.0. I think that this should be marked somehow (perhaps through a section called something like unupdated distros) or removing it from the list. I'm not sure the last one is a good option as it still technically has it.
I couldn't find much information about it so please tell me if I'm wrong.

**Comment by stefonarch** [comment]
I see in our link to rosa:

>  based on the new LXQt 0.14 

But yes, we already cleaned "dead" distro's from the list some months ago.

**Pull request closed without merging**
