### PR TITLE
Changed manjaro link

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by tsujan** [comment]
The link (https://manjaro.org/download/#lxqt-kwin) goes to XFCE here:

xfce

**Comment by tsujan** [comment]
The problem is in the webpage. When I click Editions → Community, I can reach it:

lxqt

The description is strange though: "Lightweight desktop build with the LXQt toolkit...". LXQt isn't a toolkit; Qt is.

**Comment by stefonarch** [comment]
I see, strange enough.

**Comment by tsujan** [comment]
They might correct it soon.

**Pull request closed without merging**
