### PR TITLE
updated distro list

### PR DESCRIPTION
**Pull request by stefonarch**
Removed dead chakra, added  [artix](https:artixlinux.org/), [devuan](https://pkginfo.devuan.org/cgi-bin/policy-query.html?c=package&q=lxqt) and [void](https://voidlinux.org/).

Changed link for Manjaro from https://osdn.net/projects/manjaro-community/storage/lxqt/ to the [wiki](https://wiki.manjaro.org/index.php/LXQt).

Closes https://github.com/lxqt/lxqt.github.io/issues/55

schermata-19-40-52

### CODE REVIEW

**Comment by stefonarch** [comment]
Oops I saw only now https://github.com/lxqt/lxqt.github.io/issues/52
Will include that too.

**Comment by stefonarch** [comment]
New screen:

schermata-07-51-19

**Comment by tsujan** [comment]
Looks good.

**Comment by stefonarch** [comment]
Can this be merged? I thought it was already.

**Comment by tsujan** [comment]
> I thought it was already.

And I wanted to ask why it isn't merged. Do it.

**Pull request merged**
