### PR TITLE
Update links.html

### PR DESCRIPTION
**Pull request by stefonarch**
Add Feed url

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks!

**Comment by yan12125** [comment]
I modified `bin/update-website` a little and run it. Updating lxqt-project.org should be automatic IMO.

**Comment by stefonarch** [comment]
> Updating lxqt-project.org should be automatic IMO

No idea how to achieve that.

**Comment by yan12125** [comment]
A possible way might be make lxqt-project.org an alias of lxqt.github.io https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by stefonarch** [comment]
If this makes also a redirect from lxqt.github.io to lxqt-project.org it would be ok no?

**Comment by yan12125** [comment]
I'm not sure if a redirect will work. I have no time for now on investigating each solution, so I created an issue as a reminder #48

**Pull request merged**
