### PR TITLE
Fix lxqt-openssh-askpass date

### PR DESCRIPTION
**Pull request by luis-pereira**
It was in the future.

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
> It was in the future.

People will see it tomorrow.

**Comment by tsujan** [comment]
BTW, wouldn't it be better if "Release LXQt 0.17.0" was the first item in https://lxqt-project.org?

**Comment by luis-pereira** [comment]
> BTW, wouldn't it be better if "Release LXQt 0.17.0" was the first item in https://lxqt-project.org?

This PR has that effect.
Are you taking about some some kind of permanent pin ?

**Comment by tsujan** [comment]
> Are you taking about some some kind of permanent pin ?

No, I meant exactly what you did :) Thanks!

**Pull request merged**
