### PR TITLE
debian and ubuntu blogpost; dismiss forced capitalization of titles

### PR DESCRIPTION
**Pull request by stefonarch**
Not sure about the maintainership part, if we should even mentioned it.

### CODE REVIEW

**Comment by tsujan** [comment]
> ... if we should even mentioned it.

It's a fact; isn't it?

We should just update this if LXQt starts to have a Debian maintainer — although I don't think it'll happen soon.

**Comment by stefonarch** [comment]
Something is wrong here, the post is not seen.

**Comment by stefonarch** [comment]
Just weird, locally the same, changing timestamp `date: mag 06, 2022, 11:12:32` to `date: mag 07, 2022, 11:04:39` it gets visible...

**Comment by stefonarch** [comment]
→ https://github.com/lxqt/lxqt.github.io/pull/112

**Pull request merged**
