### PR TITLE
no domain

### PR DESCRIPTION
**Pull request by jubalh**
Remove links to weblate, forum and blog.
Change download locations.

I'm not sure whether I used jekyll right :-)

### CODE REVIEW

**Comment by tsujan** [comment]
"downloadgh" looked a little strange to me -- maybe, it could be "downloadsGH" or simply "downloads" if the latter isn't already taken -- but that's unimportant.

So, GTM.

**Comment by jubalh** [comment]
Yeah there was already a "download"  (which I think is about the downstream packages) and I thought "downloads" might hard to distinguish from it. So I just quickly used "downloadgh".

**Comment by tsujan** [comment]
IMO, merge it. It's good to remove those links and tell users where they can really download the components. The site is getting cleaner and cleaner.

**Comment by jubalh** [comment]
I also did https://github.com/lxqt/lxqt.github.io/commit/6e690afdac2bece28ea63d7108c75b3a4aa79b15 for the sidebar.
Does anybody know what the old blog software was? discourse?

**Comment by luis-pereira** [comment]
> Does anybody know what the old blog software was? discourse?

Sadly, no.

**Comment by AlfredoRamos** [comment]
> Does anybody know what the old blog software was?

WordPress

**Pull request merged**
