### PR TITLE
V0.15.0

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by tsujan** [comment]
@luis-pereira 
Thank you so much for doing this! It's VERY needed for the site.

**Comment by luis-pereira** [comment]
@tsujan I will not be around for the weekend.
If someone else wants to continue... be my guest. I will continue Monday, anyway.

**Comment by tsujan** [comment]
> I will continue Monday

Great. There's no rush.

I might try to learn it if I find the time.

**Comment by luis-pereira** [comment]
Ready for merge. 
There's still lots of things to do in the site, tough.

Screenshots:

lxqt_screen3
lxqt_screen2
lxqt_screen1

**Comment by tsujan** [comment]
Very nice!

> There's still lots of things to do in the site, tough.

I think removal of the links to the inaccessible site is among them. Considering what happened, I don't think it'll be running again.

**Comment by luis-pereira** [comment]
> I think removal of the links to the inaccessible site is among them. Considering what happened, I don't think it'll be running again.

I already removed them in the release announcements  posts.
But, there are still a lot of places.

**Comment by luis-pereira** [comment]
Any objection to a merge ?

**Comment by tsujan** [comment]
None at all, from me.

**Comment by jubalh** [comment]
LGTM from me too. Thanks @luis-pereira !

**Comment by tsujan** [comment]
I took a look at it. Very nice! Who needs https://lxqt.org/ ?

**Comment by jubalh** [comment]
When we do the new point release 0.15.1 we maybe should also change lxqt-about to point to the "new" URL instead of the dead one? Or do you expect it to be functioning again in the future?
I can create a PR later today if you agree.

**Comment by tsujan** [comment]
> we maybe should also change lxqt-about to point to the "new" URL instead of the dead one?

I agree.

> Or do you expect it to be functioning again in the future?

I, for one, don't think so -- just a feeling.

**Comment by luis-pereira** [comment]
The forum was hosted in lxqt.org. That's a loss.

I have the same feeling as @tsujan

**Comment by luis-pereira** [comment]
Yes, to change the lxqt website in lxqt-about

**Comment by jubalh** [comment]
https://github.com/lxqt/lxqt-about/pull/144

BTW does someone know what was used for the blog?
Maybe we should remove the links to blog and forum for a while.
And since we have the website generated with a static site generator I don't see a reason why we didn't do that with the blog too. We could just make it live in in the _posts directory too.

**Pull request merged**
