### PR TITLE
adding application screenshots

### PR DESCRIPTION
**Pull request by stefonarch**
schermata-01-03-22-01

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
All good!

**Comment by tsujan** [comment]
Also, lxqt-archiver is quite stable. I think a screenshot of it, showing it opening its own github archive, might be good.

**Comment by stefonarch** [comment]
Sure, I just forgot it...

**Comment by stefonarch** [comment]
Done, but maybe a light palette would be better?

**Comment by tsujan** [comment]
> Done, but maybe a light palette would be better?

Dark and light palettes are both good but, IMHO, it'll be better if all tool-bar buttons are shown (the menu hides them) and the empty spaces are removed (by opening the `src` dir of `lxqt-archive` ZIP file and expanding the tree).

Another thing, that may not be related to your PR:

I think many people may not know that Qt can be styled and that they aren't limited to Fusion or its palettes. What about adding a few app screenshots (not the whole desktop) with Breeze, Kvantum and QtCurve to another section? I can provide some screenshots with Kvantum.

**Comment by tsujan** [comment]
Something like this (taken with a Kvantum theme):

lxqt-archive

**Comment by tsujan** [comment]
We can also show the right-click menu:

lxqt-archive1

**Comment by stefonarch** [comment]
I've done that in the other screens of the desktops. but probably none with kvantum engine. I could include one of the  above here, which one?

**Comment by tsujan** [comment]
The second one is better.

**Comment by tsujan** [comment]
BTW, I found a very small issue in lxqt-archiver's status-bar. Will fix it soon.

**Comment by stefonarch** [comment]
> What about adding a few app screenshots (not the whole desktop) with Breeze, Kvantum and QtCurve to another section? I can provide some screenshots with Kvantum.

I read  to fast. I don't know if the screenshots page gets overloaded with more, but we could include screens in the "theming" wiki.

archiver is pushed:

schermata-01-04-09-53

**Comment by stefonarch** [comment]
Oops, have to change Qterm... → QTerm....

**Comment by tsujan** [comment]
> but we could include screens in the "theming" wiki.

Good idea. Although it isn't a priority, it's good to show users how flexible Qt is with regard to styling.

**Pull request merged**
