### PR TITLE
CSS color revamp

### PR DESCRIPTION
**Pull request by iamthesenate1**
I have basically lighten up the colors on the website. 

Here are some screenshots:
20210626_18h41m01s_grim
20210626_18h41m13s_grim

### CODE REVIEW

**Comment by tsujan** [comment]
It would be eye-stressing for some, IMHO. The current colors look much better.

**Comment by iamthesenate1** [comment]
> It would be eye-stressing for some, IMHO. The current colors look much better.

Maybe a light mode/dark mode switch would be an option?

**Comment by tsujan** [comment]
While appreciating your contributions and hoping that they will continue, I don't see why we should change something that's already OK and elegant.

Others may have a different opinion, of course; I just told mine.

**Comment by iamthesenate1** [comment]
> While appreciating your contributions and hoping that they will continue, I don't see why we should change something that's already OK and elegant.
> 
> Others may have a different opinion, of course; I just told mine.

Ok. I'll leave this PR open for now to see other's opinions.

**Comment by stefonarch** [comment]
For the colors I agree with @tsujan. The website IMHO has more the problem of regular fresh content (a "news" section" for example) than optical restyling.

**Comment by iamthesenate1** [comment]
> For the colors I agree with @tsujan.

Ok. I'll close this PR.

> The website IMHO has more the problem of regular fresh content (a "news" section" for example) than optical restyling.

I have opened a Discussion about this. See:

**Pull request closed without merging**
