### PR TITLE
1.1.1 release

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by tsujan** [comment]
Strange that I can't see it in https://lxqt-project.org/! Is there a delay?

**Comment by stefonarch** [comment]
I'm looking at it, for some reason also locally it's 2 hours behind system(or server) time. 
It should be visible in an hour, 11:00 Europe/Rome time.
There has to be a setting

**Comment by tsujan** [comment]
I hope it isn't related to weird things I've seen in GitHub recently. On one occasion, a report totally disappeared from one of my repositories, and I'm 100% sure that I didn't delete it — I even hadn't signed in!

**Comment by stefonarch** [comment]
https://github.com/lxqt/lxqt.github.io/pull/115 it usually takes some minutes, let's see.

**Comment by stefonarch** [comment]
Nope, no clue. Still 2 hours delay. I'll remember it, actually those precise timestamps are useful only for ordering of articles, published is only the day.
Anyway, it's also sunday, so  no hurry ;)

**Comment by tsujan** [comment]
> Anyway, it's also sunday, so no hurry ;)

There's no rush at all. I'm just concerned about probable bugs in GtHub.

Let's wait a few hours...

**Comment by stefonarch** [comment]
Didn't think of it, but the site needed to be rebuilt too at 12:00.

**Comment by tsujan** [comment]
Now it's fine.

> the site needed to be rebuilt too at 12:00.

How?

**Comment by stefonarch** [comment]
Here, rerun latest job:
https://github.com/lxqt/lxqt.github.io/actions

**Comment by stefonarch** [comment]
BTW we can update trhe README for binary packages:

schermata-8 mag 16:51-01

**Pull request merged**
