### PR TITLE
Update about.html

### PR DESCRIPTION
**Pull request by stefonarch**
https://github.com/lxqt/lxqt/issues/1846#issuecomment-799571334
Some updates.

### CODE REVIEW

**Review by tsujan — APPROVED** [review]

**Comment by tsujan** [comment]
An unimportant question, out of curiosity: Is LXDE really alive (bug fixes, commits, feature implementation,...)?

**Comment by stefonarch** [comment]
https://blog.lxde.org/
https://github.com/lxde
Looks alive.

**Comment by LStranger** [comment]
> An unimportant question, out of curiosity: Is LXDE really alive (bug fixes, commits, feature implementation,...)?

Even don't think. :D It is and it will be. :D

**Comment by yan12125** [comment]
@stefonarch Looks like something goes wrong. The period after the link to our Wiki is now in a new line.

Screenshot_2021-03-17_142504

**Comment by stefonarch** [comment]
Fixed by https://github.com/lxqt/lxqt.github.io/pull/59/commits/61c636609a57c95e1b8623e02b658b1167212264, thanks!

**Comment by yan12125** [comment]
Thanks! HTML is mysterious :]

**Pull request merged**
