### PR TITLE
Updated download page

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by tsujan** [comment]
Is there a plan for releasing LXQt 1.0.1? I think it's too late for it, because of changes that aren't related to fixing critical bugs.

**Comment by stefonarch** [comment]
No sorry I got confused by arch packages numbering ` 1.0.0-1`  thought the 1.0.1 changes for globalkeys and  session were also applied to the  LXQt group, will correct.

**Comment by tsujan** [comment]
Maybe you could mention the v1.0.1 components here. I don't think we need or are able to add more v1.0.1.

**Comment by stefonarch** [comment]
> Maybe you could mention the v1.0.1 components here. I don't think we need or are able to add more v1.0.

Done, sure we don't have to release else atm, sorry for the confusion.

**Pull request merged**
