### PR TITLE
Add link for Matrix room.

### PR DESCRIPTION
**Pull request by monetaryabyss**
Per the [discussion](https://github.com/lxqt/lxqt/discussions/1923), I learned of the Matrix room. I think it would be good to add the room to the links on the web page to give it some more visibility.

### CODE REVIEW

**Comment by stefonarch** [comment]
GTM
https://github.com/lxqt/lxqt/discussions/1940
Maybe when bridging is done there is need for an overhaul of IRC/Telegram/Matrix links.

**Comment by monetaryabyss** [comment]
> Maybe when bridging is done there is need for an overhaul of IRC/Telegram/Matrix links.

That makes sense to me. I will update my PR to include the link to the Telegram group and make a note that Telgram, IRC, and Matrix are all linked together. Currently Telegram and Matrix are linked and it looks like IRC is in the works to get added very soon.

**Comment by yan12125** [comment]
Missing spaces :)

圖片

**Review by yan12125 — APPROVED** [review]
Thanks! I will update the IRC topic once this PR is merged.

**Comment by stefonarch** [comment]
I think the messengers or chats or talking or however we want to call them should be grouped.
Atm:
schermata-15-3-20:11
A draft:
schermata-15-3-20:38

**Comment by yan12125** [comment]
> I think the messengers or chats or talking or however we want to call them should be grouped.

That sounds better. I assume you already have some patch. Mind to share it?

**Comment by stefonarch** [comment]
> That sounds better. I assume you already have some patch. Mind to share it?

https://github.com/lxqt/lxqt.github.io/blob/stefonarch-patch-1/_includes/links.html

**Comment by monetaryabyss** [comment]
> > That sounds better. I assume you already have some patch. Mind to share it?
> 
> https://github.com/lxqt/lxqt.github.io/blob/stefonarch-patch-1/_includes/links.html

I agree, I think this does look better. I propose this gets merged.

**Comment by yan12125** [comment]
> https://github.com/lxqt/lxqt.github.io/blob/stefonarch-patch-1/_includes/links.html

Awesome! Could you create a PR? I had a look and it's OK, but we still need to go through the normal workflow. Also, mention this patch and the original author in the commit message will be better.

**Comment by yan12125** [comment]
Oh, Stef is again fast in response. Let's discuss at the new PR!

**Pull request closed without merging**
