### PR TITLE
Added messenger links

### PR DESCRIPTION
**Pull request by stefonarch**
Related: https://github.com/lxqt/lxqt.github.io/pull/57
Co-authored-by: https://github.com/monetaryabyss

### CODE REVIEW

**Comment by yan12125** [comment]
How about "instant messaging" instead of "messenger"?

**Comment by stefonarch** [comment]
Sounds better, yes. I thought first about "Talking" but discarded it.
Looking at the website maybe also `Discussion → Discussions`?

**Comment by yan12125** [comment]
> Looking at the website maybe also `Discussion` → `Discussions`?

Good point! Could you create another PR or add a separate commit in this PR?

**Comment by stefonarch** [comment]
Done.

**Comment by yan12125** [comment]
Thank you all!

**Comment by stefonarch** [comment]
I see that http://www.oftc.net/ doesn't work, but it looks like an issue there atm, [no link opens](https://www.qwant.com/?q=irc%20oftc.net&client=opensearch). But I oversaw that it  was still a http link and not https, but there _should_ be redirect.

**Comment by yan12125** [comment]
I remember that page was working several days ago. Looks like all OFTC websites are down, while their IRC servers are still working. I didn't receive or find an announcement, either.

**Pull request merged**
